config/routes.rb
Rails.application.routes.draw do

  root to: 'accounts#index'
  post '/accounts/:account_id/inventory/:inventory_id/items/:id/characters/:character_id', to: 'items#equip'
  resources :accounts, except: [:edit, :destroy] do
    resources :inventory, only: [:index] do
      resources :items, only: [:destroy]
    end
    resources :characters, except: [:edit]
  end
  post '/login', to: 'authentication#login'
  post '/logout', to: 'authentication#logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :characters
  has_many :equipment, through: :characters
  has_one :inventory

  has_secure_password
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :account
  has_one :equipment

  validates :name, presence: true
  validates :name, uniqueness: { scope: :account }
  validates :race, presence: true
  validates :gender, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :character
  has_many :items, as: :inside

  validates :character_id, presence: true
  validates_uniqueness_of :character_id
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :account
  has_many :items, as: :inside

  validates :account_id, presence: true
  validates_uniqueness_of :account_id
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :inside, polymorphic: true

  validates :inside_id, presence: true
  validates :inside_type, presence: true
end

app/controllers/accounts_controller.rb
require 'random_name_generator'

class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update delete]
  before_action :check_login, only: %i[show edit update delete]

  def index
    redirect_to current_user if logged_in?
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:primary] = "Account Created!"
      generate_inventory
      redirect_to @account
    else
      flash[:secondary] = @account.errors.full_messages
      redirect_to new_account_path
    end
  end

  private

  def check_login
    if !logged_in?
      redirect_to accounts_path
    elsif current_user != @account
      redirect_to current_user
    end
  end

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:email, :password, :password_confirmation)
  end

  def generate_inventory
    lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
    rng = RandomNameGenerator.new

    @account.create_inventory
    slots = %w[Weapon Armor Pet]
    5.times do
      @account.inventory.items.create(name: rng.compose(3), slot: slots.sample, rarity: rand(0..4), description: lorem)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Account.find_by_id(session[:account_id])
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ActionController::Base
  def login
    @account = Account.find_by(email: params[:email])
    if @account && @account.authenticate(params[:password])
      session[:account_id] = @account.id
      redirect_to @account
    else
      flash[:secondary] = "Email and Password combination was incorrect."
      redirect_to accounts_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/controllers/characters_controller.rb
# frozen_string_literal: true
require 'random_name_generator'

class CharactersController < ApplicationController
  before_action :set_account
  before_action :set_character, only: %i[show edit update destroy]
  before_action :character_items, only: :show
  before_action :check_login

  def index
    @characters = @account.characters.order('id ASC')
    @character = Character.new
    @character.gender = nil
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.account = @account
    @character.level = 1
    if @character.save
      flash[:primary] = ['Character Created!']
      @character.create_equipment
      randomize_equipment
    else
      flash[:secondary] = @character.errors.full_messages
    end
    redirect_to account_characters_path
  end

  def show
    @rarity_color = {
      0 => 'border-dark',
      1 => 'border-success',
      2 => 'border-info',
      3 => 'border-primary',
      4 => 'border-danger'
    }
  end

  def update
    @character.update(character_params)
    redirect_to account_characters_path
  end

  def destroy
    @character.destroy
    redirect_to account_characters_path
  end

  private

  def check_login
    if !logged_in?
      redirect_to accounts_path
    elsif current_user != @account
      redirect_to account_characters_path current_user
    end
  end

  def set_account
    @account = Account.find(params[:account_id])
  end

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name, :race, :gender)
  end

  def randomize_equipment
    lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
    rng = RandomNameGenerator.new

    slots = %w[Weapon Armor Pet]
    slots.each do |slot|
      @character.equipment.items.create(
        name: rng.compose(3),
        slot: slot,
        rarity: rand(0..4),
        description: lorem
      )
    end
  end

  def character_items
    items = @character.equipment.items
    @weapon = items.find_by(slot: "Weapon")
    @armor = items.find_by(slot: "Armor")
    @pet = items.find_by(slot: "Pet")
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  before_action :set_account
  before_action :check_login

  def index
    @inventory = current_user.inventory
    @characters = current_user.characters
    @rarity_color = {
      0 => 'border-dark',
      1 => 'border-success',
      2 => 'border-info',
      3 => 'border-primary',
      4 => 'border-danger'
    }
  end

  private

  def check_login
    if !logged_in?
      redirect_to accounts_path
    elsif current_user != @account
      redirect_to account_inventory_index_path current_user
    end
  end

  def set_account
    @account = Account.find(params[:account_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item

  def equip
    @character = Character.find(params[:character_id])
    @equips = @character.equipment
    @inventory = Account.find(params[:account_id]).inventory

    @equips.items.find_by(slot: @item.slot).update(inside: @inventory)
    @item.update(inside: @equips)

    redirect_to account_character_path(current_user, @character)
  end

  def destroy
    @item.destroy
    redirect_to account_inventory_index_path current_user
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def index
    
  end

  private

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/accounts/index.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="row justify-content-center">
      <div class="col-med alert alert-<%= key %>" role="alert"><%= value %></div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <%= image_tag "lock-xxl.png", size: "50x50", alt: "Sign In Icon", class: "d-inline-block" %>
    <div class="col-med">  
      <h3>Sign in</h3>
    </div>
  </div>
  <%= form_with url: login_path do |f|%>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">  
        <%= f.label :email %>
        <%= f.text_field :email, 
          class: 'form-control border',
          type: 'email',
          placeholder: 'Enter email address'
        %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">  
        <%= f.label :password %>
        <%= f.text_field :password,
          class: 'form-control border',
          type: 'password',
          placeholder: 'Password'
        %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">   
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="customCheck1">
          <label class="custom-control-label" for="customCheck1">Remember me</label>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">  
        <%= f.submit 'Sign In', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-12">  
      <div class="row">
        <div class="col-auto mr-auto">
          <%= link_to "Forgot Password?", '/accounts/forgot_password' %>
        </div>
        <div class="col-auto" id="sign_up">
          <%= link_to "Don't have an account? Sign up", '/accounts/new' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-med">  
      <h3>Create Account</h3>
    </div>
  </div>
  <% flash.each do |key, values| %>
    <% values.each do |value| %>
      <div class="row justify-content-center">
        <div class="col-md-5 alert alert-<%= key %>" role="alert"><%= value %></div>
      </div>
    <% end %>
  <% end %>
  <%= form_with model: @account do |f|%>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">
        <%= f.label :email %>
        <%= f.text_field :email, 
          class: 'form-control border',
          type: 'email',
          placeholder: 'Enter email address'
        %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">
        <%= f.label :password %>
        <%= f.text_field :password,
          class: 'form-control border',
          type: 'password',
          placeholder: 'Password'
        %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation,
          class: 'form-control border',
          type: 'password',
          placeholder: 'Confirm Password'
        %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">
        <%= f.submit 'Create Account', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @account.email %></h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <%= link_to "Characters", account_characters_path(current_user), class: "btn btn-primary" %>
  </div>
</div>

app/views/characters/_character_card.html.erb
<div class="character-card card">
      <%if character.gender.downcase == 'female' %>
      <%= image_tag "person-girl-outline-filled.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
    <% elsif character.gender.downcase == 'male' %>
      <%= image_tag "person-outline-filled.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
    <% else %>
      <%= image_tag "anon.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
    <% end %>
  <div class="card-body">
    <h5 class="card-title text-center"><%= character.name %></h5>
    <div class="row justify-content-between">
      <div class="col-4">
        <h6 class="card-text">Level: <%= character.level %></h6>
      </div>
      <div class="col-6 text-right">
        <h6 class="card-text">Race: <%= character.race %></h6>
      </div>
    </div>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <div class="row justify-content-between">
      <div class="col-1">
        <%= button_to "Info", account_character_path(@account, character), method: "get", class: "btn btn-primary" %>
      </div>
      <div class="col-1">
        <%= button_to "Delete", account_character_path(@account, character), method: "delete", class: "btn btn-secondary delete-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/characters/_equipment_card.html.erb
<div class="equipment-card card">
  <% case equipment.slot %>
  <% when "Weapon" %>
    <%= image_tag "sword.png", size: "180x180", alt: "Weapon Picture", class: "card-img-top mx-auto item-border #{@rarity_color[equipment.rarity]}"  %>
  <% when "Armor" %>
    <%= image_tag "armor.png", size: "180x180", alt: "Armor Picture", class: "card-img-top mx-auto item-border #{@rarity_color[equipment.rarity]}" %>
  <% when "Pet" %>
    <%= image_tag "cat.png", size: "180x180", alt: "Pet Picture", class: "card-img-top mx-auto item-border #{@rarity_color[equipment.rarity]}" %>
  <% else %>
    <%= image_tag "sack.png", size: "180x180", alt: "Pet Picture", class: "card-img-top mx-auto" %>
  <% end %>
  <div class="card-body">
    <h4 class="card-title"><%= equipment.name %></h4>
    <p class="card-text"><%= equipment.description %></p>
  </div>
</div>

app/views/characters/_new_character_card.html.erb
<div class="character-card card">
  <%= image_tag "anon.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
  <div class="card-body">
    <%= form_for [account, character] do |f| %>
      <div class="row">
        <div class="col">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control border', type: 'text', placeholder: 'Enter a name' %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.label :race %>
          <%= f.select :race, ["Human", "Plant", "Mutant", "Merloc"], {}, {class: "form-control"} %>
        </div>
        <div class="col">
          <%= f.label :gender %>
          <%= f.select :gender, ["Male", "Female", "Other"], {}, {class: "form-control"} %>
          </div>
      </div>
      <div class="row">
        <div class="col">
          <%= button_tag( class: "btn btn-float btn-primary create-btn") do %>
            <i class="material-icons">add</i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<div class="container">
  <% flash.each do |key, values| %>
    <% values.each do |value| %>
      <div class="row justify-content-center">
        <div class="col-md-5 alert alert-<%= key %>" role="alert"><%= value %></div>
      </div>
    <% end %>
  <% end %>
  <div class="card-deck justify-content-center">
    <% @characters.each do |character| %>
      <%= render partial: "character_card", locals: { character: character } %>
    <% end %>
    <%= render partial: "new_character_card", locals: { account: @account, character: @character } %>
  </div>
</div>

app/views/characters/show.html.erb
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="detail-card card">
      <%if @character.gender.downcase == 'female' %>
        <%= image_tag "person-girl-outline-filled.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
      <% elsif @character.gender.downcase == 'male' %>
        <%= image_tag "person-outline-filled.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
      <% else %>
        <%= image_tag "anon.png", size: "256x256", alt: "Race Picture", class: "card-img-top mx-auto" %>
      <% end %>
      <div class="card-body">
        <%= form_for [@account, @character] do |f| %>
          <div class="row">
            <div class="col">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control border', type: 'text'%>
            </div>
            <div class="col">
              <%= f.label :level %>
              <%= f.text_field :level, class: 'form-control border', type: 'text', disabled: true %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.label :race %>
              <%= f.select :race, ["Human", "Plant", "Mutant", "Merloc"], {}, { class: "form-control" } %>
            </div>
            <div class="col">
              <%= f.label :gender %>
              <%= f.select :gender, ["Male", "Female", "Other"], {}, { class: "form-control" } %>
              </div>
          </div>
          <div class="row justify-content-between">
            <div class="col-1">
              <%= button_to "Update", account_character_path(@account, @character), method: "update", class: "btn btn-primary" %>
            </div>
            <div class="col-1">
              <%= button_to "Delete", account_character_path(@account, @character), method: "delete", class: "btn btn-secondary delete-btn" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-7 col-md-8 col-sm-12 ">
    <h3>Equipment</h3>
    <div class="row justify-content-left">
      <div class="col-lg col-md col-sm-8">
        <h5> Weapon </h5>
        <%= render partial: "equipment_card", locals: { equipment: @weapon } %>
      </div>
      <div class="col-lg col-md col-sm-8">
        <h5> Armor </h5>
        <%= render partial: "equipment_card", locals: { equipment: @armor } %>
      </div>
      <div class="col-lg col-md col-sm-8">
        <h5> Pet </h5>
        <%= render partial: "equipment_card", locals: { equipment: @pet } %>
      </div>
    </div>
  </div>
</div>

app/views/inventory/_inventory_card.html.erb
<div class="inventory-card card">
  <% case item.slot %>
  <% when "Weapon" %>
    <%= image_tag "sword.png", size: "180x180", alt: "Weapon Picture", class: "card-img-top mx-auto item-border #{@rarity_color[item.rarity]} " %>
  <% when "Armor" %>
    <%= image_tag "armor.png", size: "180x180", alt: "Armor Picture", class: "card-img-top mx-auto item-border #{@rarity_color[item.rarity]} " %>
  <% when "Pet" %>
    <%= image_tag "cat.png", size: "180x180", alt: "Pet Picture", class: "card-img-top mx-auto item-border #{@rarity_color[item.rarity]} " %>
  <% end %>
  <div class="card-body">
    <h4 class="card-title text-center"><%= item.name %></h4>
  </div>
  <div class="card-actions justify-content-between">
    <form method="post" action="/articles/new" class="button_to">
      <div class="dropup">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Equip
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% @characters.each do |character| %>
            <% url = "/accounts/#{current_user.id}/inventory/#{current_user.inventory.id}/items/#{item.id}/characters/#{character.id}" %>
            <%= link_to character.name, url, method: :post, class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
    </form>
    <div>
      <%= button_to "Sell", account_inventory_item_path(@account, @account.inventory, item), class: "btn btn-outline-secondary", method: :delete %>
    </div>
  </div>
</div>

app/views/inventory/index.html.erb
<div class="container">
  <h3>Inventory</h3>
  <div class="card-deck">
    <% @inventory.items.each do |item| %>
      <%= render partial: "inventory_card", locals: { item: item } %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minion Master</title>
    <%= favicon_link_tag 'monster.png' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="initial-scale=1, shrink-to-fit=no, width=device-width" name="viewport">

    <!-- CSS -->
    <!-- Add Material font (Roboto) and Material icon as needed -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i|Roboto+Mono:300,400,700|Roboto+Slab:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Add Material CSS, replace Bootstrap CSS -->
    <link href="path_to/material.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "monster.png", size: "50x50", alt: "Monster Logo", class: "d-inline-block align-top" %>
        Minion Master
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
          <% if logged_in? %>
            <%= link_to "Profile", current_user, class: "nav-link nav-item" %>
            <%= link_to "Characters", account_characters_path(current_user), class: "nav-link nav-item active" %>
            <%= link_to "Inventory", account_inventory_index_path(current_user), class: "nav-link nav-item" %>
          <% end %>
        </div>
        <% if logged_in? %>
          <span>
            <%= button_to "Logout", logout_path, method: "post", class: "btn btn-secondary nav-link" %>
          </span>
        <% else %>
          <span>
            <%= button_to "Sign In", accounts_path, method: "get", class: "btn btn-primary nav-link" %>
          </span>
        <% end %>
          
      </div>
    </nav>

    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <!-- Then Material JavaScript on top of Bootstrap JavaScript -->
    <script src="path_to/material.min.js"></script>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    
  </div>
</div>